name: CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.go'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.go'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
      - name: Run golangci-lint
        run: golangci-lint run ./...